# Optimize for the current CPU with aggressive optimizations
# This will automatically enable AVX512 if your CPU supports it
# The binary will be optimized for your CPU but may not run on older CPUs
# For maximum compatibility, compile without this file (or set RUSTFLAGS="")
#
# Fast-math optimizations (equivalent to C++ -ffast-math):
# - Enables unsafe floating-point optimizations for better performance
# - May reduce numerical precision in edge cases

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "llvm-args=--ffast-math",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "llvm-args=--ffast-math",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "llvm-args=--ffast-math",
]

# For other architectures, use default settings
