[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx512f"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx512f"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx512f"]

# For other architectures, use default settings (no AVX512)
